use_frameworks!
inhibit_all_warnings!

platform :ios, '13.0'

pod 'SwiftLint'

target 'Chaos_Example' do
  pod 'ChaosCore', :path => '../'
  pod 'ChaosNet', :path => '../'
  pod 'ChaosUi', :path => '../'
  pod 'ChaosKit', :path => '../'
end
