use_frameworks!
inhibit_all_warnings!

platform :ios, '13.0'

pod 'SwiftLint'

target 'Chaos_Example' do
  pod 'ChaosCore', :path => '../'
  pod 'ChaosNet', :path => '../'
  pod 'ChaosUi', :path => '../'
  pod 'ChaosKit', :path => '../'

  target 'Chaos_Tests' do
  end
end

post_install do |pi|
  pi.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
